package com.nukkitx.protocol.bedrock.v363;

import com.nukkitx.protocol.bedrock.BedrockPacketCodec;
import com.nukkitx.protocol.bedrock.packet.*;
import com.nukkitx.protocol.bedrock.v363.serializer.*;
import lombok.experimental.UtilityClass;

@UtilityClass
public class Bedrock_v363 {
    public static BedrockPacketCodec V363_CODEC = BedrockPacketCodec.builder()
            .protocolVersion(363)
            .minecraftVersion("1.12.60")
            .headerSerializer(PacketHeaderSerializer_v363.INSTANCE)
            .registerPacket(LoginPacket.class, LoginSerializer_v363.INSTANCE, 1)
            .registerPacket(PlayStatusPacket.class, PlayStatusSerializer_v363.INSTANCE, 2)
            .registerPacket(ServerToClientHandshakePacket.class, ServerToClientHandshakeSerializer_v363.INSTANCE, 3)
            .registerPacket(ClientToServerHandshakePacket.class, ClientToServerHandshakeSerializer_v363.INSTANCE, 4)
            .registerPacket(DisconnectPacket.class, DisconnectSerializer_v363.INSTANCE, 5)
            .registerPacket(ResourcePacksInfoPacket.class, ResourcePacksInfoSerializer_v363.INSTANCE, 6)
            .registerPacket(ResourcePackStackPacket.class, ResourcePackStackSerializer_v363.INSTANCE, 7)
            .registerPacket(ResourcePackClientResponsePacket.class, ResourcePackClientResponseSerializer_v363.INSTANCE, 8)
            .registerPacket(TextPacket.class, TextSerializer_v363.INSTANCE, 9)
            .registerPacket(SetTimePacket.class, SetTimeSerializer_v363.INSTANCE, 10)
            .registerPacket(StartGamePacket.class, StartGameSerializer_v363.INSTANCE, 11)
            .registerPacket(AddPlayerPacket.class, AddPlayerSerializer_v363.INSTANCE, 12)
            .registerPacket(AddEntityPacket.class, AddEntitySerializer_v363.INSTANCE, 13)
            .registerPacket(RemoveEntityPacket.class, RemoveEntitySerializer_v363.INSTANCE, 14)
            .registerPacket(AddItemEntityPacket.class, AddItemEntitySerializer_v363.INSTANCE, 15)
            .registerPacket(TakeItemEntityPacket.class, TakeItemEntitySerializer_v363.INSTANCE, 17)
            .registerPacket(MoveEntityAbsolutePacket.class, MoveEntityAbsoluteSerializer_v363.INSTANCE, 18)
            .registerPacket(MovePlayerPacket.class, MovePlayerSerializer_v363.INSTANCE, 19)
            .registerPacket(RiderJumpPacket.class, RiderJumpSerializer_v363.INSTANCE, 20)
            .registerPacket(UpdateBlockPacket.class, UpdateBlockSerializer_v363.INSTANCE, 21)
            .registerPacket(AddPaintingPacket.class, AddPaintingSerializer_v363.INSTANCE, 22)
            .registerPacket(ExplodePacket.class, ExplodeSerializer_v363.INSTANCE, 23)
            .registerPacket(LevelSoundEvent1Packet.class, LevelSoundEvent1Serializer_v363.INSTANCE, 24)
            .registerPacket(LevelEventPacket.class, LevelEventSerializer_v363.INSTANCE, 25)
            .registerPacket(BlockEventPacket.class, BlockEventSerializer_v363.INSTANCE, 26)
            .registerPacket(EntityEventPacket.class, EntityEventSerializer_v363.INSTANCE, 27)
            .registerPacket(MobEffectPacket.class, MobEffectSerializer_v363.INSTANCE, 28)
            .registerPacket(UpdateAttributesPacket.class, UpdateAttributesSerializer_v363.INSTANCE, 29)
            .registerPacket(InventoryTransactionPacket.class, InventoryTransactionSerializer_v363.INSTANCE, 30)
            .registerPacket(MobEquipmentPacket.class, MobEquipmentSerializer_v363.INSTANCE, 31)
            .registerPacket(MobArmorEquipmentPacket.class, MobArmorEquipmentSerializer_v363.INSTANCE, 32)
            .registerPacket(InteractPacket.class, InteractSerializer_v363.INSTANCE, 33)
            .registerPacket(BlockPickRequestPacket.class, BlockPickRequestSerializer_v363.INSTANCE, 34)
            .registerPacket(EntityPickRequestPacket.class, EntityPickRequestSerializer_v363.INSTANCE, 35)
            .registerPacket(PlayerActionPacket.class, PlayerActionSerializer_v363.INSTANCE, 36)
            .registerPacket(EntityFallPacket.class, EntityFallSerializer_v363.INSTANCE, 37)
            .registerPacket(HurtArmorPacket.class, HurtArmorSerializer_v363.INSTANCE, 38)
            .registerPacket(SetEntityDataPacket.class, SetEntityDataSerializer_v363.INSTANCE, 39)
            .registerPacket(SetEntityMotionPacket.class, SetEntityMotionSerializer_v363.INSTANCE, 40)
            .registerPacket(SetEntityLinkPacket.class, SetEntityLinkSerializer_v363.INSTANCE, 41)
            .registerPacket(SetHealthPacket.class, SetHealthSerializer_v363.INSTANCE, 42)
            .registerPacket(SetSpawnPositionPacket.class, SetSpawnPositionSerializer_v363.INSTANCE, 43)
            .registerPacket(AnimatePacket.class, AnimateSerializer_v363.INSTANCE, 44)
            .registerPacket(RespawnPacket.class, RespawnSerializer_v363.INSTANCE, 45)
            .registerPacket(ContainerOpenPacket.class, ContainerOpenSerializer_v363.INSTANCE, 46)
            .registerPacket(ContainerClosePacket.class, ContainerCloseSerializer_v363.INSTANCE, 47)
            .registerPacket(PlayerHotbarPacket.class, PlayerHotbarSerializer_v363.INSTANCE, 48)
            .registerPacket(InventoryContentPacket.class, InventoryContentSerializer_v363.INSTANCE, 49)
            .registerPacket(InventorySlotPacket.class, InventorySlotSerializer_v363.INSTANCE, 50)
            .registerPacket(ContainerSetDataPacket.class, ContainerSetDataSerializer_v363.INSTANCE, 51)
            .registerPacket(CraftingDataPacket.class, CraftingDataSerializer_v363.INSTANCE, 52)
            .registerPacket(CraftingEventPacket.class, CraftingEventSerializer_v363.INSTANCE, 53)
            .registerPacket(GuiDataPickItemPacket.class, GuiDataPickItemSerializer_v363.INSTANCE, 54)
            .registerPacket(AdventureSettingsPacket.class, AdventureSettingsSerializer_v363.INSTANCE, 55)
            .registerPacket(BlockEntityDataPacket.class, BlockEntityDataSerializer_v363.INSTANCE, 56)
            .registerPacket(PlayerInputPacket.class, PlayerInputSerializer_v363.INSTANCE, 57)
            .registerPacket(LevelChunkPacket.class, LevelChunkSerializer_v363.INSTANCE, 58)
            .registerPacket(SetCommandsEnabledPacket.class, SetCommandsEnabledSerializer_v363.INSTANCE, 59)
            .registerPacket(SetDifficultyPacket.class, SetDifficultySerializer_v363.INSTANCE, 60)
            .registerPacket(ChangeDimensionPacket.class, ChangeDimensionSerializer_v363.INSTANCE, 61)
            .registerPacket(SetPlayerGameTypePacket.class, SetPlayerGameTypeSerializer_v363.INSTANCE, 62)
            .registerPacket(PlayerListPacket.class, PlayerListSerializer_v363.INSTANCE, 63)
            .registerPacket(SimpleEventPacket.class, SimpleEventSerializer_v363.INSTANCE, 64)
            .registerPacket(EventPacket.class, EventSerializer_v363.INSTANCE, 65)
            .registerPacket(SpawnExperienceOrbPacket.class, SpawnExperienceOrbSerializer_v363.INSTANCE, 66)
            .registerPacket(ClientboundMapItemDataPacket.class, ClientboundMapItemDataSerializer_v363.INSTANCE, 67)
            .registerPacket(MapInfoRequestPacket.class, MapInfoRequestSerializer_v363.INSTANCE, 68)
            .registerPacket(RequestChunkRadiusPacket.class, RequestChunkRadiusSerializer_v363.INSTANCE, 69)
            .registerPacket(ChunkRadiusUpdatedPacket.class, ChunkRadiusUpdatedSerializer_v363.INSTANCE, 70)
            .registerPacket(ItemFrameDropItemPacket.class, ItemFrameDropItemSerializer_v363.INSTANCE, 71)
            .registerPacket(GameRulesChangedPacket.class, GameRulesChangedSerializer_v363.INSTANCE, 72)
            .registerPacket(CameraPacket.class, CameraSerializer_v363.INSTANCE, 73)
            .registerPacket(BossEventPacket.class, BossEventSerializer_v363.INSTANCE, 74)
            .registerPacket(ShowCreditsPacket.class, ShowCreditsSerializer_v363.INSTANCE, 75)
            .registerPacket(AvailableCommandsPacket.class, AvailableCommandsSerializer_v363.INSTANCE, 76)
            .registerPacket(CommandRequestPacket.class, CommandRequestSerializer_v363.INSTANCE, 77)
            .registerPacket(CommandBlockUpdatePacket.class, CommandBlockUpdateSerializer_v363.INSTANCE, 78)
            .registerPacket(CommandOutputPacket.class, CommandOutputSerializer_v363.INSTANCE, 79)
            .registerPacket(UpdateTradePacket.class, UpdateTradeSerializer_v363.INSTANCE, 80)
            .registerPacket(UpdateEquipPacket.class, UpdateEquipSerializer_v363.INSTANCE, 81)
            .registerPacket(ResourcePackDataInfoPacket.class, ResourcePackDataInfoSerializer_v363.INSTANCE, 82)
            .registerPacket(ResourcePackChunkDataPacket.class, ResourcePackChunkDataSerializer_v363.INSTANCE, 83)
            .registerPacket(ResourcePackChunkRequestPacket.class, ResourcePackChunkRequestSerializer_v363.INSTANCE, 84)
            .registerPacket(TransferPacket.class, TransferSerializer_v363.INSTANCE, 85)
            .registerPacket(PlaySoundPacket.class, PlaySoundSerializer_v363.INSTANCE, 86)
            .registerPacket(StopSoundPacket.class, StopSoundSerializer_v363.INSTANCE, 87)
            .registerPacket(SetTitlePacket.class, SetTitleSerializer_v363.INSTANCE, 88)
            .registerPacket(AddBehaviorTreePacket.class, AddBehaviorTreeSerializer_v363.INSTANCE, 89)
            .registerPacket(StructureBlockUpdatePacket.class, StructureBlockUpdateSerializer_v363.INSTANCE, 90)
            .registerPacket(ShowStoreOfferPacket.class, ShowStoreOfferSerializer_v363.INSTANCE, 91)
            .registerPacket(PurchaseReceiptPacket.class, PurchaseReceiptSerializer_v363.INSTANCE, 92)
            .registerPacket(PlayerSkinPacket.class, PlayerSkinSerializer_v363.INSTANCE, 93)
            .registerPacket(SubClientLoginPacket.class, SubClientLoginSerializer_v363.INSTANCE, 94)
            .registerPacket(AutomationClientConnectPacket.class, AutomationClientConnectSerializer_v363.INSTANCE, 95)
            .registerPacket(SetLastHurtByPacket.class, SetLastHurtBySerializer_v363.INSTANCE, 96)
            .registerPacket(BookEditPacket.class, BookEditSerializer_v363.INSTANCE, 97)
            .registerPacket(NpcRequestPacket.class, NpcRequestSerializer_v363.INSTANCE, 98)
            .registerPacket(PhotoTransferPacket.class, PhotoTransferSerializer_v363.INSTANCE, 99)
            .registerPacket(ModalFormRequestPacket.class, ModalFormRequestSerializer_v363.INSTANCE, 100)
            .registerPacket(ModalFormResponsePacket.class, ModalFormResponseSerializer_v363.INSTANCE, 101)
            .registerPacket(ServerSettingsRequestPacket.class, ServerSettingsRequestSerializer_v363.INSTANCE, 102)
            .registerPacket(ServerSettingsResponsePacket.class, ServerSettingsResponseSerializer_v363.INSTANCE, 103)
            .registerPacket(ShowProfilePacket.class, ShowProfileSerializer_v363.INSTANCE, 104)
            .registerPacket(SetDefaultGameTypePacket.class, SetDefaultGameTypeSerializer_v363.INSTANCE, 105)
            .registerPacket(RemoveObjectivePacket.class, RemoveObjectiveSerializer_v363.INSTANCE, 106)
            .registerPacket(SetDisplayObjectivePacket.class, SetDisplayObjectiveSerializer_v363.INSTANCE, 107)
            .registerPacket(SetScorePacket.class, SetScoreSerializer_v363.INSTANCE, 108)
            .registerPacket(LabTablePacket.class, LabTableSerializer_v363.INSTANCE, 109)
            .registerPacket(UpdateBlockSyncedPacket.class, UpdateBlockSyncedSerializer_v363.INSTANCE, 110)
            .registerPacket(MoveEntityDeltaPacket.class, MoveEntityDeltaSerializer_v363.INSTANCE, 111)
            .registerPacket(SetScoreboardIdentityPacket.class, SetScoreboardIdentitySerializer_v363.INSTANCE, 112)
            .registerPacket(SetLocalPlayerAsInitializedPacket.class, SetLocalPlayerAsInitializedSerializer_v363.INSTANCE, 113)
            .registerPacket(UpdateSoftEnumPacket.class, UpdateSoftEnumSerializer_v363.INSTANCE, 114)
            .registerPacket(NetworkStackLatencyPacket.class, NetworkStackLatencySerializer_v363.INSTANCE, 115)
            .registerPacket(ScriptCustomEventPacket.class, ScriptCustomEventSerializer_v363.INSTANCE, 117)
            .registerPacket(SpawnParticleEffectPacket.class, SpawnParticleEffectSerializer_v363.INSTANCE, 118)
            .registerPacket(AvailableEntityIdentifiersPacket.class, AvailableEntityIdentifiersSerializer_v363.INSTANCE, 119)
            .registerPacket(LevelSoundEvent2Packet.class, LevelSoundEvent2Serializer_v363.INSTANCE, 120)
            .registerPacket(NetworkChunkPublisherUpdatePacket.class, NetworkChunkPublisherUpdateSerializer_v363.INSTANCE, 121)
            .registerPacket(BiomeDefinitionListPacket.class, BiomeDefinitionListSerializer_v363.INSTANCE, 122)
            .registerPacket(LevelSoundEventPacket.class, LevelSoundEvent3Serializer_v363.INSTANCE, 123)
            .registerPacket(LevelEventGenericPacket.class, LevelEventGenericSerializer_v363.INSTANCE, 124)
            .registerPacket(LecternUpdatePacket.class, LecternUpdateSerializer_v363.INSTANCE, 125)
            .registerPacket(VideoStreamConnectPacket.class, VideoStreamConnectSerializer_v363.INSTANCE, 126)
            // AddEntityPacket 127
            // RemoveEntityPacket 128
            .registerPacket(ClientCacheStatusPacket.class, ClientCacheStatusSerializer_v363.INSTANCE, 129)
            .registerPacket(OnScreenTextureAnimationPacket.class, OnScreenTextureAnimationSerializer_v363.INSTANCE, 130)
            .registerPacket(MapCreateLockedCopyPacket.class, MapCreateLockedCopySerializer_v363.INSTANCE, 131)
            .registerPacket(StructureTemplateDataExportRequestPacket.class, StructureTemplateDataExportRequestSerializer_v363.INSTANCE, 132)
            .registerPacket(StructureTemplateDataExportResponsePacket.class, StructureTemplateDataExportResponseSerializer_v363.INSTANCE, 133)
            .registerPacket(UpdateBlockPropertiesPacket.class, UpdateBlockPropertiesSerializer_v363.INSTANCE, 134)
            .registerPacket(ClientCacheBlobStatusPacket.class, ClientCacheBlobStatusSerializer_v363.INSTANCE, 135)
            .registerPacket(ClientCacheMissResponsePacket.class, ClientCacheMissResponseSerializer_v363.INSTANCE, 136)

            .registerPacket(EducationSettingsPacket.class, EducationSettingsSerializer_v363.INSTANCE, 137)
            .registerPacket(EmotePacket.class, EmoteSerializer_v363.INSTANCE, 138)
            .registerPacket(MultiplayerSettingsPacket.class, MultiplayerSettingsSerializer_v363.INSTANCE, 139)
            .registerPacket(SettingsCommandPacket.class, SettingsCommandSerializer_v363.INSTANCE, 140)
            .registerPacket(AnvilDamagePacket.class, AnvilDamageSerializer_v363.INSTANCE, 141)
            .registerPacket(CompletedUsingItemPacket.class, CompletedUsingItemSerializer_v363.INSTANCE, 142)
            .registerPacket(NetworkSettingsPacket.class, NetworkSettingsSerializer_v363.INSTANCE, 143)
            .registerPacket(PlayerAuthInputPacket.class, PlayerAuthInputSerializer_v363.INSTANCE, 144)
            .build();
}
