package com.nukkitx.protocol.bedrock.v291;

import com.nukkitx.protocol.bedrock.BedrockPacketCodec;
import com.nukkitx.protocol.bedrock.packet.*;
import com.nukkitx.protocol.bedrock.v291.packet.*;
import lombok.experimental.UtilityClass;

@UtilityClass
public class Bedrock_v291 {
    public static BedrockPacketCodec V219_CODEC = BedrockPacketCodec.builder()
            .addCompatibleVersion(219)
            .packetHeader(PacketHeader_v291::new)
            .registerPacket(LoginPacket.class, LoginPacket_v291::new, 1)
            .registerPacket(PlayStatusPacket.class, PlayStatusPacket_v291::new, 2)
            .registerPacket(ServerToClientHandshakePacket.class, ServerToClientHandshakePacket_v291::new, 3)
            .registerPacket(ClientToServerHandshakePacket.class, ClientToServerHandshakePacket_v291::new, 4)
            .registerPacket(DisconnectPacket.class, DisconnectPacket_v291::new, 5)
            .registerPacket(ResourcePacksInfoPacket.class, ResourcePacksInfoPacket_v291::new, 6)
            .registerPacket(ResourcePackStackPacket.class, ResourcePackStackPacket_v291::new, 7)
            .registerPacket(ResourcePackClientResponsePacket.class, ResourcePackClientResponsePacket_v291::new, 8)
            .registerPacket(TextPacket.class, TextPacket_v291::new, 9)
            .registerPacket(SetTimePacket.class, SetTimePacket_v291::new, 10)
            .registerPacket(StartGamePacket.class, StartGamePacket_v291::new, 11)
            .registerPacket(AddPlayerPacket.class, AddPlayerPacket_v291::new, 12)
            .registerPacket(AddEntityPacket.class, AddEntityPacket_v291::new, 13)
            .registerPacket(RemoveEntityPacket.class, RemoveEntityPacket_v291::new, 14)
            .registerPacket(AddItemEntityPacket.class, AddItemEntityPacket_v291::new, 15)
            .registerPacket(AddHangingEntityPacket.class, AddHangingEntityPacket_v291::new, 16)
            .registerPacket(TakeItemEntityPacket.class, TakeItemEntityPacket_v291::new, 17)
            .registerPacket(MoveEntityAbsolutePacket.class, MoveEntityAbsolutePacket_v291::new, 18)
            .registerPacket(MovePlayerPacket.class, MovePlayerPacket_v291::new, 19)
            .registerPacket(RiderJumpPacket.class, RiderJumpPacket_v291::new, 20)
            .registerPacket(UpdateBlockPacket.class, UpdateBlockPacket_v291::new, 21)
            .registerPacket(AddPaintingPacket.class, AddPaintingPacket_v291::new, 22)
            .registerPacket(ExplodePacket.class, ExplodePacket_v291::new, 23)
            .registerPacket(LevelSoundEventPacket.class, LevelSoundEventPacket_v291::new, 24)
            .registerPacket(LevelEventPacket.class, LevelEventPacket_v291::new, 25)
            .registerPacket(BlockEventPacket.class, BlockEventPacket_v291::new, 26)
            .registerPacket(EntityEventPacket.class, EntityEventPacket_v291::new, 27)
            .registerPacket(MobEffectPacket.class, MobEffectPacket_v291::new, 28)
            .registerPacket(UpdateAttributesPacket.class, UpdateAttributesPacket_v291::new, 29)
            .registerPacket(InventoryTransactionPacket.class, InventoryTransactionPacket_v291::new, 30)
            .registerPacket(MobEquipmentPacket.class, MobEquipmentPacket_v291::new, 31)
            .registerPacket(MobArmorEquipmentPacket.class, MobArmorEquipmentPacket_v291::new, 32)
            .registerPacket(InteractPacket.class, InteractPacket_v291::new, 33)
            .registerPacket(BlockPickRequestPacket.class, BlockPickRequestPacket_v291::new, 34)
            .registerPacket(EntityPickRequestPacket.class, EntityPickRequestPacket_v291::new, 35)
            .registerPacket(PlayerActionPacket.class, PlayerActionPacket_v291::new, 36)
            .registerPacket(EntityFallPacket.class, EntityFallPacket_v291::new, 37)
            .registerPacket(HurtArmorPacket.class, HurtArmorPacket_v291::new, 38)
            .registerPacket(SetEntityDataPacket.class, SetEntityDataPacket_v291::new, 39)
            .registerPacket(SetEntityMotionPacket.class, SetEntityMotionPacket_v291::new, 40)
            .registerPacket(SetEntityLinkPacket.class, SetEntityLinkPacket_v291::new, 41)
            .registerPacket(SetHealthPacket.class, SetHealthPacket_v291::new, 42)
            .registerPacket(SetSpawnPositionPacket.class, SetSpawnPositionPacket_v291::new, 43)
            .registerPacket(AnimatePacket.class, AnimatePacket_v291::new, 44)
            .registerPacket(RespawnPacket.class, RespawnPacket_v291::new, 45)
            .registerPacket(ContainerOpenPacket.class, ContainerOpenPacket_v291::new, 46)
            .registerPacket(ContainerClosePacket.class, ContainerClosePacket_v291::new, 47)
            .registerPacket(PlayerHotbarPacket.class, PlayerHotbarPacket_v291::new, 48)
            .registerPacket(InventoryContentPacket.class, InventoryContentPacket_v291::new, 49)
            .registerPacket(InventorySlotPacket.class, InventorySlotPacket_v291::new, 50)
            .registerPacket(ContainerSetDataPacket.class, ContainerSetDataPacket_v291::new, 51)
            .registerPacket(CraftingDataPacket.class, CraftingDataPacket_v291::new, 52)
            .registerPacket(CraftingEventPacket.class, CraftingEventPacket_v291::new, 53)
            .registerPacket(GuiDataPickItemPacket.class, GuiDataPickItemPacket_v291::new, 54)
            .registerPacket(AdventureSettingsPacket.class, AdventureSettingsPacket_v291::new, 55)
            .registerPacket(BlockEntityDataPacket.class, BlockEntityDataPacket_v291::new, 56)
            .registerPacket(PlayerInputPacket.class, PlayerInputPacket_v291::new, 57)
            .registerPacket(FullChunkDataPacket.class, FullChunkDataPacket_v291::new, 58)
            .registerPacket(SetCommandsEnabledPacket.class, SetCommandsEnabledPacket_v291::new, 59)
            .registerPacket(SetDifficultyPacket.class, SetDifficultyPacket_v291::new, 60)
            .registerPacket(ChangeDimensionPacket.class, ChangeDimensionPacket_v291::new, 61)
            .registerPacket(SetPlayerGameTypePacket.class, SetPlayerGameTypePacket_v291::new, 62)
            .registerPacket(PlayerListPacket.class, PlayerListPacket_v291::new, 63)
            .registerPacket(SimpleEventPacket.class, SimpleEventPacket_v291::new, 64)
            .registerPacket(EventPacket.class, EventPacket_v291::new, 65)
            .registerPacket(SpawnExperienceOrbPacket.class, SpawnExperienceOrbPacket_v291::new, 66)
            .registerPacket(ClientboundMapItemDataPacket.class, ClientboundMapItemDataPacket_v291::new, 67)
            .registerPacket(MapInfoRequestPacket.class, MapInfoRequestPacket_v291::new, 68)
            .registerPacket(RequestChunkRadiusPacket.class, RequestChunkRadiusPacket_v291::new, 69)
            .registerPacket(ChunkRadiusUpdatedPacket.class, ChunkRadiusUpdatedPacket_v291::new, 70)
            .registerPacket(ItemFrameDropItemPacket.class, ItemFrameDropItemPacket_v291::new, 71)
            .registerPacket(GameRulesChangedPacket.class, GameRulesChangedPacket_v291::new, 72)
            .registerPacket(CameraPacket.class, CameraPacket_v291::new, 73)
            .registerPacket(BossEventPacket.class, BossEventPacket_v291::new, 74)
            .registerPacket(ShowCreditsPacket.class, ShowCreditsPacket_v291::new, 75)
            .registerPacket(AvailableCommandsPacket.class, AvailableCommandsPacket_v291::new, 76)
            .registerPacket(CommandRequestPacket.class, CommandRequestPacket_v291::new, 77)
            .registerPacket(CommandBlockUpdatePacket.class, CommandBlockUpdatePacket_v291::new, 78)
            .registerPacket(CommandOutputPacket.class, CommandOutputPacket_v291::new, 79)
            .registerPacket(UpdateTradePacket.class, UpdateTradePacket_v291::new, 80)
            .registerPacket(UpdateEquipPacket.class, UpdateEquipPacket_v291::new, 81)
            .registerPacket(ResourcePackDataInfoPacket.class, ResourcePackDataInfoPacket_v291::new, 82)
            .registerPacket(ResourcePackChunkDataPacket.class, ResourcePackChunkDataPacket_v291::new, 83)
            .registerPacket(ResourcePackChunkRequestPacket.class, ResourcePackChunkRequestPacket_v291::new, 84)
            .registerPacket(TransferPacket.class, TransferPacket_v291::new, 85)
            .registerPacket(PlaySoundPacket.class, PlaySoundPacket_v291::new, 86)
            .registerPacket(StopSoundPacket.class, StopSoundPacket_v291::new, 87)
            .registerPacket(SetTitlePacket.class, SetTitlePacket_v291::new, 88)
            .registerPacket(AddBehaviorTreePacket.class, AddBehaviorTreePacket_v291::new, 89)
            .registerPacket(StructureBlockUpdatePacket.class, StructureBlockUpdatePacket_v291::new, 90)
            .registerPacket(ShowStoreOfferPacket.class, ShowStoreOfferPacket_v291::new, 91)
            .registerPacket(PurchaseReceiptPacket.class, PurchaseReceiptPacket_v291::new, 92)
            .registerPacket(PlayerSkinPacket.class, PlayerSkinPacket_v291::new, 93)
            .registerPacket(SubClientLoginPacket.class, SubClientLoginPacket_v291::new, 94)
            .registerPacket(WSConnectPacket.class, WSConnectPacket_v291::new, 95)
            .registerPacket(SetLastHurtByPacket.class, SetLastHurtByPacket_v291::new, 96)
            .registerPacket(BookEditPacket.class, BookEditPacket_v291::new, 97)
            .registerPacket(NpcRequestPacket.class, NpcRequestPacket_v291::new, 98)
            .registerPacket(PhotoTransferPacket.class, PhotoTransferPacket_v291::new, 99)
            .registerPacket(ModalFormRequestPacket.class, ModalFormRequestPacket_v291::new, 100)
            .registerPacket(ModalFormResponsePacket.class, ModalFormResponsePacket_v291::new, 101)
            .registerPacket(ServerSettingsRequestPacket.class, ServerSettingsRequestPacket_v291::new, 102)
            .registerPacket(ServerSettingsResponsePacket.class, ServerSettingsResponsePacket_v291::new, 103)
            .registerPacket(ShowProfilePacket.class, ShowProfilePacket_v291::new, 104)
            .registerPacket(SetDefaultGameTypePacket.class, SetDefaultGameTypePacket_v291::new, 105)
            .registerPacket(RemoveObjectivePacket.class, RemoveObjectivePacket_v291::new, 106)
            .registerPacket(SetDisplayObjectivePacket.class, SetDisplayObjectivePacket_v291::new, 107)
            .registerPacket(SetScorePacket.class, SetScorePacket_v291::new, 108)
            .registerPacket(LabTablePacket.class, LabTablePacket_v291::new, 109)
            .registerPacket(UpdateBlockSyncedPacket.class, UpdateBlockSyncedPacket_v291::new, 110)
            .registerPacket(MoveEntityDeltaPacket.class, MoveEntityDeltaPacket_v291::new, 111)
            .registerPacket(SetScoreboardIdentityPacket.class, SetScoreboardIdentityPacket_v291::new, 112)
            .registerPacket(SetLocalPlayerAsInitializedPacket.class, SetLocalPlayerAsInitializedPacket_v291::new, 113)
            .registerPacket(UpdateSoftEnumPacket.class, UpdateSoftEnumPacket_v291::new, 114)
            .registerPacket(NetworkStackLatencyPacket.class, NetworkStackLatencyPacket_v291::new, 115)
            .registerPacket(ScriptCustomEventPacket.class, ScriptCustomEventPacket_v291::new, 117)
            .build();
}
