package org.cloudburstmc.protocol.java.v754;

import lombok.experimental.UtilityClass;
import org.cloudburstmc.protocol.java.JavaPacketCodec;
import org.cloudburstmc.protocol.java.packet.State;
import org.cloudburstmc.protocol.java.packet.handshake.*;
import org.cloudburstmc.protocol.java.packet.login.*;
import org.cloudburstmc.protocol.java.packet.play.CustomPayloadPacket;
import org.cloudburstmc.protocol.java.packet.play.KeepAlivePacket;
import org.cloudburstmc.protocol.java.packet.play.SetCarriedItemPacket;
import org.cloudburstmc.protocol.java.packet.play.clientbound.*;
import org.cloudburstmc.protocol.java.packet.play.ContainerClosePacket;
import org.cloudburstmc.protocol.java.packet.play.serverbound.*;
import org.cloudburstmc.protocol.java.packet.status.*;
import org.cloudburstmc.protocol.java.v754.serializer.handshake.*;
import org.cloudburstmc.protocol.java.v754.serializer.login.*;
import org.cloudburstmc.protocol.java.v754.serializer.play.clientbound.*;
import org.cloudburstmc.protocol.java.v754.serializer.play.*;
import org.cloudburstmc.protocol.java.v754.serializer.play.serverbound.*;
import org.cloudburstmc.protocol.java.v754.serializer.status.*;

@UtilityClass
public class Java_v754 {
    public static final JavaPacketCodec V754_CODEC = JavaPacketCodec.builder()
            .protocolVersion(754)
            .minecraftVersion("1.16.4")
            .helper(JavaPacketHelper_v754.INSTANCE)
            .codec(State.HANDSHAKING, JavaPacketCodec.JavaStateCodec.builder()
                    .registerServerbound(HandshakingPacket.class, HandshakingSerializer_v754.INSTANCE, 0)
                    // .registerClientbound(LegacyServerListPingPacket.class, LegacyServerListPingSerializer_v754.INSTANCE, 254) // TODO
                    .build())
            .codec(State.STATUS, JavaPacketCodec.JavaStateCodec.builder()
                    .registerClientbound(StatusResponsePacket.class, StatusResponseSerializer_v754.INSTANCE, 0)
                    .registerClientbound(PongPacket.class, PongSerializer_v754.INSTANCE, 1)
                    .registerServerbound(StatusRequestPacket.class, StatusRequestSerializer_v754.INSTANCE, 0)
                    .registerServerbound(PingPacket.class, PingSerializer_v754.INSTANCE, 1)
                    .build())
            .codec(State.LOGIN, JavaPacketCodec.JavaStateCodec.builder()
                    .registerClientbound(org.cloudburstmc.protocol.java.packet.login.DisconnectPacket.class, org.cloudburstmc.protocol.java.v754.serializer.login.DisconnectSerializer_v754.INSTANCE, 0)
                    .registerClientbound(EncryptionRequestPacket.class, EncryptionRequestSerializer_v754.INSTANCE, 1)
                    .registerClientbound(LoginSuccessPacket.class, LoginSuccessSerializer_v754.INSTANCE, 2)
                    .registerClientbound(SetCompressionPacket.class, SetCompressionSerializer_v754.INSTANCE, 3)
                    .registerClientbound(CustomQueryRequestPacket.class, CustomQueryRequestSerializer_v754.INSTANCE, 4)
                    .registerServerbound(LoginStartPacket.class, LoginStartSerializer_v754.INSTANCE, 0)
                    .registerServerbound(EncryptionResponsePacket.class, EncryptionResponseSerializer_v754.INSTANCE, 1)
                    .registerServerbound(CustomQueryResponsePacket.class, CustomQueryResponseSerializer_v754.INSTANCE, 2)
                    .build())
            .codec(State.PLAY, JavaPacketCodec.JavaStateCodec.builder()
                    .registerClientbound(AddEntityPacket.class, AddEntitySerializer_v754.INSTANCE, 0)
                    .registerClientbound(AddExperienceOrbPacket.class, AddExperienceOrbSerializer_v754.INSTANCE, 1)
                    .registerClientbound(AddMobPacket.class, AddMobSerializer_v754.INSTANCE, 2)
                    .registerClientbound(AddPaintingPacket.class, AddPaintingSerializer_v754.INSTANCE, 3)
                    .registerClientbound(AddPlayerPacket.class, AddPlayerSerializer_v754.INSTANCE, 4)
                    .registerClientbound(AnimatePacket.class, AnimateSerializer_v754.INSTANCE, 5)
                    .registerClientbound(AwardStatsPacket.class, AwardStatsSerializer_v754.INSTANCE, 6)
                    .registerClientbound(BlockBreakAckPacket.class, BlockBreakAckSerializer_v754.INSTANCE, 7)
                    .registerClientbound(BlockDestructionPacket.class, BlockDestructionSerializer_v754.INSTANCE, 8)
                    .registerClientbound(BlockEntityDataPacket.class, BlockEntityDataSerializer_v754.INSTANCE, 9)
                    .registerClientbound(BlockEventPacket.class, BlockEventSerializer_v754.INSTANCE, 10)
                    .registerClientbound(BlockUpdatePacket.class, BlockUpdateSerializer_v754.INSTANCE, 11)
                    .registerClientbound(BossEventPacket.class, BossEventSerializer_v754.INSTANCE, 12)
                    .registerClientbound(ChangeDifficultyPacket.class, ChangeDifficultySerializer_v754.INSTANCE, 13)
                    .registerClientbound(ServerChatPacket.class, ServerChatSerializer_v754.INSTANCE, 14)
                    .registerClientbound(CommandSuggestionsPacket.class, CommandSuggestionsSerializer_v754.INSTANCE, 15)
                    .registerClientbound(CommandsPacket.class, CommandsSerializer_v754.INSTANCE, 16)
                    .registerClientbound(ContainerAckPacket.class, ContainerAckSerializer_v754.INSTANCE, 17)
                    .registerClientbound(ContainerClosePacket.class, ContainerCloseSerializer_v754.INSTANCE, 18)
                    .registerClientbound(ContainerSetContentPacket.class, ContainerSetContentSerializer_v754.INSTANCE, 19)
                    .registerClientbound(ContainerSetDataPacket.class, ContainerSetDataSerializer_v754.INSTANCE, 20)
                    .registerClientbound(ContainerSetSlotPacket.class, ContainerSetSlotSerializer_v754.INSTANCE, 21)
                    .registerClientbound(CooldownPacket.class, CooldownSerializer_v754.INSTANCE, 22)
                    .registerClientbound(CustomPayloadPacket.class, CustomPayloadSerializer_v754.INSTANCE, 23)
                    .registerClientbound(CustomSoundPacket.class, CustomSoundSerializer_v754.INSTANCE, 24)
                    .registerClientbound(org.cloudburstmc.protocol.java.packet.play.clientbound.DisconnectPacket.class, org.cloudburstmc.protocol.java.v754.serializer.play.clientbound.DisconnectSerializer_v754.INSTANCE, 25)
                    .registerClientbound(EntityEventPacket.class, EntityEventSerializer_v754.INSTANCE, 26)
                    .registerClientbound(ExplodePacket.class, ExplodeSerializer_v754.INSTANCE, 27)
                    .registerClientbound(ForgetLevelChunkPacket.class, ForgetLevelChunkSerializer_v754.INSTANCE, 28)
                    .registerClientbound(GameEventPacket.class, GameEventSerializer_v754.INSTANCE, 29)
                    .registerClientbound(HorseScreenOpenPacket.class, HorseScreenOpenSerializer_v754.INSTANCE, 30)
                    .registerClientbound(KeepAlivePacket.class, KeepAliveSerializer_v754.INSTANCE, 31)
                    .registerClientbound(LevelChunkPacket.class, LevelChunkSerializer_v754.INSTANCE, 32)
                    .registerClientbound(LevelEventPacket.class, LevelEventSerializer_v754.INSTANCE, 33)
                    .registerClientbound(LevelParticlesPacket.class, LevelParticlesSerializer_v754.INSTANCE, 34)
                    .registerClientbound(LightUpdatePacket.class, LightUpdateSerializer_v754.INSTANCE, 35)
                    .registerClientbound(LoginPacket.class, LoginSerializer_v754.INSTANCE, 36)
                    .registerClientbound(MapItemDataPacket.class, MapItemDataSerializer_v754.INSTANCE, 37)
                    .registerClientbound(MerchantOffersPacket.class, MerchantOffersSerializer_v754.INSTANCE, 38)
                    .registerClientbound(MoveEntityPacket.Pos.class, MoveEntitySerializer_v754.Pos.INSTANCE, 39)
                    .registerClientbound(MoveEntityPacket.PosRot.class, MoveEntitySerializer_v754.PosRot.INSTANCE, 40)
                    .registerClientbound(MoveEntityPacket.Rot.class, MoveEntitySerializer_v754.Rot.INSTANCE, 41)
                    .registerClientbound(MoveEntityPacket.class, MoveEntitySerializer_v754.Noop.INSTANCE, 42)
                    .registerClientbound(MoveVehiclePacket.class, MoveVehicleSerializer_v754.INSTANCE, 43)
                    .registerClientbound(OpenBookPacket.class, OpenBookSerializer_v754.INSTANCE, 44)
                    .registerClientbound(OpenScreenPacket.class, OpenScreenSerializer_v754.INSTANCE, 45)
                    .registerClientbound(OpenSignEditorPacket.class, OpenSignEditorSerializer_v754.INSTANCE, 46)
                    .registerClientbound(PlaceGhostRecipePacket.class, PlaceGhostRecipeSerializer_v754.INSTANCE, 47)
                    .registerClientbound(PlayerAbilitiesPacket.class, PlayerAbilitiesSerializer_v754.INSTANCE, 48)
                    .registerClientbound(PlayerCombatPacket.class, PlayerCombatSerializer_v754.INSTANCE, 49)
                    .registerClientbound(PlayerInfoPacket.class, PlayerInfoSerializer_v754.INSTANCE, 50)
                    .registerClientbound(PlayerLookAtPacket.class, PlayerLookAtSerializer_v754.INSTANCE, 51)
                    .registerClientbound(PlayerPositionPacket.class, PlayerPositionSerializer_v754.INSTANCE, 52)
                    .registerClientbound(RecipePacket.class, RecipeSerializer_v754.INSTANCE, 53)
                    .registerClientbound(RemoveEntitiesPacket.class, RemoveEntitiesSerializer_v754.INSTANCE, 54)
                    .registerClientbound(RemoveMobEffectPacket.class, RemoveMobEffectSerializer_v754.INSTANCE, 55)
                    .registerClientbound(ResourcePackPacket.class, ResourcePackSerializer_v754.INSTANCE, 56)
                    .registerClientbound(RespawnPacket.class, RespawnSerializer_v754.INSTANCE, 57)
                    .registerClientbound(RotateHeadPacket.class, RotateHeadSerializer_v754.INSTANCE, 58)
                    .registerClientbound(SectionBlocksUpdatePacket.class, SectionBlocksUpdateSerializer_v754.INSTANCE, 59)
                    .registerClientbound(SelectAdvancementsTabPacket.class, SelectAdvancementsTabSerializer_v754.INSTANCE, 60)
                    .registerClientbound(SetBorderPacket.class, SetBorderSerializer_v754.INSTANCE, 61)
                    .registerClientbound(SetCameraPacket.class, SetCameraSerializer_v754.INSTANCE, 62)
                    .registerClientbound(SetCarriedItemPacket.class, SetCarriedItemSerializer_v754.INSTANCE, 63)
                    .registerClientbound(SetChunkCacheCenterPacket.class, SetChunkCacheCenterSerializer_v754.INSTANCE, 64)
                    .registerClientbound(SetChunkCacheRadiusPacket.class, SetChunkCacheRadiusSerializer_v754.INSTANCE, 65)
                    .registerClientbound(SetDefaultSpawnPositionPacket.class, SetDefaultSpawnPositionSerializer_v754.INSTANCE, 66)
                    .registerClientbound(SetDisplayObjectivePacket.class, SetDisplayObjectiveSerializer_v754.INSTANCE, 67)
                    .registerClientbound(SetEntityDataPacket.class, SetEntityDataSerializer_v754.INSTANCE, 68)
                    .registerClientbound(SetEntityLinkPacket.class, SetEntityLinkSerializer_v754.INSTANCE, 69)
                    .registerClientbound(SetEntityMotionPacket.class, SetEntityMotionSerializer_v754.INSTANCE, 70)
                    .registerClientbound(SetEquipmentPacket.class, SetEquipmentSerializer_v754.INSTANCE, 71)
                    .registerClientbound(SetExperiencePacket.class, SetExperienceSerializer_v754.INSTANCE, 72)
                    .registerClientbound(SetHealthPacket.class, SetHealthSerializer_v754.INSTANCE, 73)
                    .registerClientbound(SetObjectivePacket.class, SetObjectiveSerializer_v754.INSTANCE, 74)
                    .registerClientbound(SetPassengersPacket.class, SetPassengersSerializer_v754.INSTANCE, 75)
                    .registerClientbound(SetPlayerTeamPacket.class, SetPlayerTeamSerializer_v754.INSTANCE, 76)
                    .registerClientbound(SetScorePacket.class, SetScoreSerializer_v754.INSTANCE, 77)
                    .registerClientbound(SetTimePacket.class, SetTimeSerializer_v754.INSTANCE, 78)
                    .registerClientbound(SetTitlesPacket.class, SetTitlesSerializer_v754.INSTANCE, 79)

                    .registerServerbound(AcceptTeleportationPacket.class, AcceptTeleportationSerializer_v754.INSTANCE, 0)
                    .registerServerbound(ClientChatPacket.class, ClientChatSerializer_v754.INSTANCE, 3)
                    .registerServerbound(ClientCommandPacket.class, ClientCommandSerializer_v754.INSTANCE, 4)
                    .registerServerbound(ClientInformationPacket.class, ClientInformationSerializer_v754.INSTANCE, 5)
                    .registerServerbound(ContainerClickPacket.class, ContainerClickSerializer_v754.INSTANCE, 9)
                    .registerServerbound(ContainerClosePacket.class, ContainerCloseSerializer_v754.INSTANCE, 10)
                    .registerServerbound(CustomPayloadPacket.class, CustomPayloadSerializer_v754.INSTANCE, 11)
                    .registerServerbound(KeepAlivePacket.class, KeepAliveSerializer_v754.INSTANCE, 16)
                    .registerServerbound(MovePlayerPacket.Pos.class, MovePlayerSerializer_v754.Pos.INSTANCE, 18)
                    .registerServerbound(MovePlayerPacket.PosRot.class, MovePlayerSerializer_v754.PosRot.INSTANCE, 19)
                    .registerServerbound(MovePlayerPacket.Rot.class, MovePlayerSerializer_v754.Rot.INSTANCE, 20)
                    .registerServerbound(PlayerActionPacket.class, PlayerActionSerializer_v754.INSTANCE, 27)
                    .registerServerbound(RecipeBookChangeSettingsPacket.class, RecipeBookChangeSettingsSerializer_v754.INSTANCE, 30)
                    .registerServerbound(SeenAdvancementsPacket.class, SeenAdvancementsSerializer_v754.INSTANCE, 34)
                    .registerServerbound(SetCarriedItemPacket.class, SetCarriedItemSerializer_v754.INSTANCE, 37)
                    .build()
            ).build();
}
